server:
  port: 3232

spring:
  data:
    maria:
      jdbc-url: jdbc:mariadb://ec2-13-209-15-90.ap-northeast-2.compute.amazonaws.com:3306/test?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: shouldoc
  jpa:
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true
